spring:
  data:
    mongodb:
      uri: mongodb://edwin:password@localhost:27017/?authSource=admin&authMechanism=SCRAM-SHA-1
      database: auth
#      host: auth-mongodb
#      host: localhost
#      username: user
#      username: edwin
#      password: ${MONGODB_PASSWORD}
#      password: password
#      database: piggymetrics
#      database: auth
#      auth: admin
#      port: 27017

server:
  servlet:
    context-path: /uaa
  port: 5000
